// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC80NrpRycx4AHFcyaVGkJYbUs83tZcnug',
    appId: '1:373287637880:web:6e9c7e94aafb2577fe6e8d',
    messagingSenderId: '373287637880',
    projectId: 'vocalendar-a0ae2',
    authDomain: 'vocalendar-a0ae2.firebaseapp.com',
    storageBucket: 'vocalendar-a0ae2.firebasestorage.app',
    measurementId: 'G-ZV1Y9J9C3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKonwRcLKCmjHO-6ZqcR9QAe16-LGHPV8',
    appId: '1:373287637880:android:7929837c7a09348dfe6e8d',
    messagingSenderId: '373287637880',
    projectId: 'vocalendar-a0ae2',
    storageBucket: 'vocalendar-a0ae2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQQxnlEf62M4sT2GAJ0YKV1Q3uracJWo',
    appId: '1:373287637880:ios:1c7355579a08383dfe6e8d',
    messagingSenderId: '373287637880',
    projectId: 'vocalendar-a0ae2',
    storageBucket: 'vocalendar-a0ae2.firebasestorage.app',
    iosBundleId: 'com.example.flutterapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtQQxnlEf62M4sT2GAJ0YKV1Q3uracJWo',
    appId: '1:373287637880:ios:1c7355579a08383dfe6e8d',
    messagingSenderId: '373287637880',
    projectId: 'vocalendar-a0ae2',
    storageBucket: 'vocalendar-a0ae2.firebasestorage.app',
    iosBundleId: 'com.example.flutterapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC80NrpRycx4AHFcyaVGkJYbUs83tZcnug',
    appId: '1:373287637880:web:f9c9880dee44d57afe6e8d',
    messagingSenderId: '373287637880',
    projectId: 'vocalendar-a0ae2',
    authDomain: 'vocalendar-a0ae2.firebaseapp.com',
    storageBucket: 'vocalendar-a0ae2.firebasestorage.app',
    measurementId: 'G-SQZVZ8D5S5',
  );

}